name: Build and Deploy Petclinic

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: |
          echo "Checking Maven version:"
          mvn --version
          echo "Checking Java version:"
          java --version
          echo "Checking if Tomcat is running:"
          curl -I localhost:8080

  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: |
          echo "Building the Maven package."
          mvn clean package

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to tomcat
        run: |
          mvn deploy9:tomcat


